import { getDocsList, getDocContent, extractH1FromContent } from './github-docs';
import { slugify } from './utils';

export interface DocItem {
  title: string;
  path: string;
  slug: string;
  category: 'quickstart' | 'tutorials' | 'use-cases' | 'api-reference';
  githubPath: string;
  children?: DocItem[];
}

export interface DocsManifest {
  categories: {
    quickstart: DocItem[];
    tutorials: DocItem[];
    'use-cases': DocItem[];
    'api-reference': DocItem[];
  };
  allDocs: DocItem[];
}

/**
 * Determine category and slug from file path and H1 title
 */
function mapPathToSlug(path: string, h1Title: string): { slug: string; category: DocItem['category']; title: string } {
  // Remove docs/ prefix and file extension
  const cleanPath = path.replace(/^docs\//, '').replace(/\.(rst|md)$/, '');
  
  // Generate slug from H1 title
  const titleSlug = slugify(h1Title);
  
  // Check for tutorials directory
  if (cleanPath.startsWith('tutorials/')) {
    return {
      slug: `tutorials/${titleSlug}`,
      category: 'tutorials',
      title: h1Title,
    };
  }
  
  // Check for use-cases directory (handle both use-cases and use_cases)
  if (cleanPath.startsWith('use-cases/') || cleanPath.startsWith('use_cases/')) {
    return {
      slug: `use-cases/${titleSlug}`,
      category: 'use-cases',
      title: h1Title,
    };
  }
  
  // Quick start files (can be in root or quickstart directory)
  if (cleanPath.includes('quickstart') || cleanPath.includes('quick_start')) {
    return {
      slug: `quickstart/${titleSlug}`,
      category: 'quickstart',
      title: h1Title,
    };
  }
  
  // Root-level files default to tutorials
  return {
    slug: `tutorials/${titleSlug}`,
    category: 'tutorials',
    title: h1Title,
  };
}

/**
 * Filter out auto-generated API docs and other files we don't want
 */
function shouldIncludeDoc(path: string): boolean {
  // Exclude auto-generated API docs
  if (path.includes('_autogen') || path.includes('autogenerated')) {
    return false;
  }
  
  // Exclude specific files and directories
  const excluded = [
    'conf.py',
    'index.rst',
    'index.md',
    'Makefile',
    '_static',
    '_templates',
    '_build',
    '.git',
  ];
  
  if (excluded.some((ex) => path.includes(ex))) {
    return false;
  }
  
  // Include all markdown/rst files in docs directory
  // We'll categorize them based on their path
  return path.startsWith('docs/') && (path.endsWith('.md') || path.endsWith('.rst'));
}

/**
 * Generate documentation manifest from GitHub file list
 */
export async function generateDocsManifest(): Promise<DocsManifest> {
  try {
    const files = await getDocsList();
    
    if (!files || files.length === 0) {
      return {
        categories: {
          quickstart: [],
          tutorials: [],
          'use-cases': [],
          'api-reference': [],
        },
        allDocs: [],
      };
    }
    
    const filteredFiles = files.filter((file) => shouldIncludeDoc(file.path));
    
    // Fetch content and extract H1 title for each file
    const docsPromises = filteredFiles.map(async (file) => {
      try {
        const content = await getDocContent(file.path);
        const h1Title = extractH1FromContent(content);
        const { slug, category, title } = mapPathToSlug(file.path, h1Title);
        return {
          title,
          path: file.path,
          slug,
          category,
          githubPath: file.path,
        };
      } catch (error) {
        // Fallback to filename-based title if content fetch fails
        const fallbackTitle = file.path.split('/').pop()?.replace(/\.(rst|md)$/, '') || 'Documentation';
        const { slug, category, title } = mapPathToSlug(file.path, fallbackTitle);
        return {
          title,
          path: file.path,
          slug,
          category,
          githubPath: file.path,
        };
      }
    });
    
    const docs = (await Promise.all(docsPromises))
      .sort((a, b) => a.title.localeCompare(b.title));

    // Group by category
    const categories = {
      quickstart: docs.filter((d) => d.category === 'quickstart'),
      tutorials: docs.filter((d) => d.category === 'tutorials'),
      'use-cases': docs.filter((d) => d.category === 'use-cases'),
      'api-reference': docs.filter((d) => d.category === 'api-reference'),
    };

    return {
      categories,
      allDocs: docs,
    };
  } catch (error) {
    throw error;
  }
}

/**
 * Find a doc by slug
 */
export function findDocBySlug(manifest: DocsManifest, slug: string): DocItem | undefined {
  return manifest.allDocs.find((doc) => doc.slug === slug);
}

/**
 * Get the navigation structure for the sidebar
 */
export function getNavStructure(manifest: DocsManifest) {
  return [
    {
      title: 'Quick Start',
      path: '/docs/tutorials/quickstart',
      children: manifest.categories.quickstart.map((doc) => ({
        title: doc.title,
        path: `/docs/${doc.slug}`,
      })),
    },
    {
      title: 'Tutorials',
      path: '/docs/tutorials',
      children: manifest.categories.tutorials.map((doc) => ({
        title: doc.title,
        path: `/docs/${doc.slug}`,
      })),
    },
    {
      title: 'Use Cases',
      path: '/docs/use-cases',
      children: manifest.categories['use-cases'].map((doc) => ({
        title: doc.title,
        path: `/docs/${doc.slug}`,
      })),
    },
    {
      title: 'ReadTheDocs Reference',
      path: 'https://opentimelineio.readthedocs.io/en/latest/',
      external: true,
    },
  ];
}

/**
 * Get previous and next documents for navigation (constrained within the current category)
 */
export function getPreviousNextDocs(manifest: DocsManifest, currentSlug: string): {
  previous: DocItem | null;
  next: DocItem | null;
} {
  const currentDoc = findDocBySlug(manifest, currentSlug);
  
  if (!currentDoc) {
    return { previous: null, next: null };
  }
  
  // Get all documents in the current category
  const categoryDocs = manifest.categories[currentDoc.category] || [];
  
  // Find the current document's index within its category
  const currentIndex = categoryDocs.findIndex((doc) => doc.slug === currentSlug);
  
  if (currentIndex === -1) {
    return { previous: null, next: null };
  }
  
  // Get previous and next within the same category
  const previous = currentIndex > 0 ? categoryDocs[currentIndex - 1] : null;
  const next = currentIndex < categoryDocs.length - 1 ? categoryDocs[currentIndex + 1] : null;
  
  return { previous, next };
}

/**
 * Get category display name
 */
export function getCategoryDisplayName(category: DocItem['category']): string {
  const categoryMap: Record<DocItem['category'], string> = {
    quickstart: 'Quick Start',
    tutorials: 'Tutorials',
    'use-cases': 'Use Cases',
    'api-reference': 'API Reference',
  };
  return categoryMap[category] || category;
}

