import { getDocsList } from './github-docs';

export interface DocItem {
  title: string;
  path: string;
  slug: string;
  category: 'quickstart' | 'tutorials' | 'use-cases' | 'api-reference';
  githubPath: string;
  children?: DocItem[];
}

export interface DocsManifest {
  categories: {
    quickstart: DocItem[];
    tutorials: DocItem[];
    'use-cases': DocItem[];
    'api-reference': DocItem[];
  };
  allDocs: DocItem[];
}

/**
 * Map file paths to friendly slugs and categories
 */
function mapPathToSlug(path: string): { slug: string; category: DocItem['category']; title: string } {
  // Remove docs/ prefix and file extension
  const cleanPath = path.replace(/^docs\//, '').replace(/\.(rst|md)$/, '');
  
  // Helper to format title from filename
  const formatTitle = (filename: string): string => {
    return filename
      .replace(/[-_]/g, ' ')
      .replace(/\b\w/g, (l) => l.toUpperCase());
  };
  
  // Check for tutorials directory
  if (cleanPath.startsWith('tutorials/')) {
    const filename = cleanPath.replace(/^tutorials\//, '');
    return {
      slug: `tutorials/${filename}`,
      category: 'tutorials',
      title: formatTitle(filename),
    };
  }
  
  // Check for use-cases directory (handle both use-cases and use_cases)
  if (cleanPath.startsWith('use-cases/') || cleanPath.startsWith('use_cases/')) {
    const filename = cleanPath.replace(/^use-cases\//, '').replace(/^use_cases\//, '');
    return {
      slug: `use-cases/${filename}`,
      category: 'use-cases',
      title: formatTitle(filename),
    };
  }
  
  // Quick start files (can be in root or quickstart directory)
  if (cleanPath.includes('quickstart') || cleanPath.includes('quick_start')) {
    const filename = cleanPath.includes('/') ? cleanPath.split('/').pop()! : cleanPath;
    return {
      slug: `quickstart/${filename}`,
      category: 'quickstart',
      title: formatTitle(filename),
    };
  }
  
  // Root-level files default to tutorials
  const filename = cleanPath.includes('/') ? cleanPath.split('/').pop()! : cleanPath;
  return {
    slug: `tutorials/${filename}`,
    category: 'tutorials',
    title: formatTitle(filename),
  };
}

/**
 * Filter out auto-generated API docs and other files we don't want
 */
function shouldIncludeDoc(path: string): boolean {
  // Exclude auto-generated API docs
  if (path.includes('_autogen') || path.includes('autogenerated')) {
    return false;
  }
  
  // Exclude specific files and directories
  const excluded = [
    'conf.py',
    'index.rst',
    'index.md',
    'Makefile',
    '_static',
    '_templates',
    '_build',
    '.git',
  ];
  
  if (excluded.some((ex) => path.includes(ex))) {
    return false;
  }
  
  // Include all markdown/rst files in docs directory
  // We'll categorize them based on their path
  return path.startsWith('docs/') && (path.endsWith('.md') || path.endsWith('.rst'));
}

/**
 * Generate documentation manifest from GitHub file list
 */
export async function generateDocsManifest(): Promise<DocsManifest> {
  try {
    const files = await getDocsList();
    
    console.log(`[Docs Manifest] Found ${files.length} total files from GitHub`);
    
    if (!files || files.length === 0) {
      console.warn('No documentation files found in GitHub repository');
      return {
        categories: {
          quickstart: [],
          tutorials: [],
          'use-cases': [],
          'api-reference': [],
        },
        allDocs: [],
      };
    }
    
    const filteredFiles = files.filter((file) => shouldIncludeDoc(file.path));
    console.log(`[Docs Manifest] After filtering: ${filteredFiles.length} files`);
    
    const docs: DocItem[] = filteredFiles
      .map((file) => {
        const { slug, category, title } = mapPathToSlug(file.path);
        return {
          title,
          path: file.path,
          slug,
          category,
          githubPath: file.path,
        };
      })
      .sort((a, b) => a.title.localeCompare(b.title));

    // Debug: Log some examples
    if (docs.length > 0) {
      console.log(`[Docs Manifest] Sample docs:`, docs.slice(0, 5).map(d => ({
        path: d.githubPath,
        slug: d.slug,
        category: d.category,
        title: d.title,
      })));
    }

    // Group by category
    const categories = {
      quickstart: docs.filter((d) => d.category === 'quickstart'),
      tutorials: docs.filter((d) => d.category === 'tutorials'),
      'use-cases': docs.filter((d) => d.category === 'use-cases'),
      'api-reference': docs.filter((d) => d.category === 'api-reference'),
    };

    console.log(`[Docs Manifest] Categorized:`, {
      quickstart: categories.quickstart.length,
      tutorials: categories.tutorials.length,
      'use-cases': categories['use-cases'].length,
      'api-reference': categories['api-reference'].length,
      total: docs.length,
    });

    return {
      categories,
      allDocs: docs,
    };
  } catch (error) {
    console.error('Error generating docs manifest:', error);
    throw error;
  }
}

/**
 * Find a doc by slug
 */
export function findDocBySlug(manifest: DocsManifest, slug: string): DocItem | undefined {
  return manifest.allDocs.find((doc) => doc.slug === slug);
}

/**
 * Get the navigation structure for the sidebar
 */
export function getNavStructure(manifest: DocsManifest) {
  return [
    {
      title: 'Quick Start',
      path: '/docs/quickstart',
      children: manifest.categories.quickstart.map((doc) => ({
        title: doc.title,
        path: `/docs/${doc.slug}`,
      })),
    },
    {
      title: 'Tutorials',
      path: '/docs/tutorials',
      children: manifest.categories.tutorials.map((doc) => ({
        title: doc.title,
        path: `/docs/${doc.slug}`,
      })),
    },
    {
      title: 'Use Cases',
      path: '/docs/use-cases',
      children: manifest.categories['use-cases'].map((doc) => ({
        title: doc.title,
        path: `/docs/${doc.slug}`,
      })),
    },
    {
      title: 'API Reference',
      path: 'https://opentimelineio.readthedocs.io/en/latest/',
      external: true,
    },
  ];
}

