/**
 * Extract h1 and h2 headings from markdown content
 * 
 * Note: This uses the same slugify logic as the markdown renderer
 * to ensure IDs match what's generated by rehypeSlug
 */
export interface TocItem {
  id: string;
  text: string;
  level: 1 | 2;
}

// Same slugify function as in markdown-renderer.tsx
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function extractHeadings(markdown: string): TocItem[] {
  const headings: TocItem[] = [];
  const lines = markdown.split('\n');
  const idCounts = new Map<string, number>();
  
  for (const line of lines) {
    const trimmed = line.trim();
    
    // Match h1 (# Title) or h2 (## Title)
    const h1Match = trimmed.match(/^#\s+(.+)$/);
    const h2Match = trimmed.match(/^##\s+(.+)$/);
    
    if (h1Match) {
      const text = h1Match[1].trim();
      const baseId = slugify(text);
      
      // Handle duplicate IDs (same as rehypeSlug behavior)
      // First occurrence gets baseId, subsequent ones get -1, -2, etc.
      const count = idCounts.get(baseId) || 0;
      const id = count > 0 ? `${baseId}-${count}` : baseId;
      idCounts.set(baseId, count + 1);
      
      headings.push({
        id,
        text,
        level: 1,
      });
    } else if (h2Match) {
      const text = h2Match[1].trim();
      const baseId = slugify(text);
      
      // Handle duplicate IDs (same as rehypeSlug behavior)
      // First occurrence gets baseId, subsequent ones get -1, -2, etc.
      const count = idCounts.get(baseId) || 0;
      const id = count > 0 ? `${baseId}-${count}` : baseId;
      idCounts.set(baseId, count + 1);
      
      headings.push({
        id,
        text,
        level: 2,
      });
    }
  }
  
  return headings;
}

